frontend smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -351,14 +351,23 @@ jobs:
       - run:
           name: Frontend smoke test.
           command: |
-            FRONTEND_URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-            echo ${FRONTEND_URL} 
-            if curl -s ${FRONTEND_URL} | grep "Welcome"
-            then
-              exit 0
-            else
-              exit 1
-            fi
+              URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+              echo ${URL} 
+              if curl -s ${URL} | grep "Welcome"
+              then
+                  # Change this to 0 after the job fails
+                return 1
+              else
+                return 1
+              fi
+            # FRONTEND_URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            # echo ${FRONTEND_URL} 
+            # if curl -s ${FRONTEND_URL} | grep "Welcome"
+            # then
+            #   exit 0
+            # else
+            #   exit 1
+            # fi
       - destroy-environment
       - revert-migrations
 
